CREATE TABLE IF NOT EXISTS anime
(
    id              INT NOT NULL,
    title           VARCHAR(255),
    link            VARCHAR(255),
    image           VARCHAR(255),
    score           DOUBLE,
    members         INT,
    genre           VARCHAR(255),
    studios         VARCHAR(255),
    source          VARCHAR(255),
    season          VARCHAR(7),
    year            INT,
    rank            INT,
    popularity      INT,
    scoring_count   INT,
    episodes        INT,
    air_status      VARCHAR(255),
    type            VARCHAR(50),
    start_date      DATETIME,
    end_date        DATETIME,
    english_title   VARCHAR(1000),
    japanese_title  VARCHAR(1000),
    synopsis        TEXT,
    created_at      DATETIME,
    updated_at      DATETIME,
    large_image     VARCHAR(255),
    rating          VARCHAR(50),
    nsfw            VARCHAR(50),
    PRIMARY KEY (id)
);
