myanimelist:
  clientId: ${myanimelist_clientid}

discord:
  webhookUrl: ${discord_webhookurl}

eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${serviceregistry_url}

management:
  endpoints:
    web:
      exposure:
        include: '*'
