myanimelist:
  clientId: ${myanimechart_myanimelist_client_id}

discord:
  webhookUrl: ${myanimechart_discord_webhook_url}

eureka:
  instance:
    hostname: localhost
    non-secure-port-enabled: true
    secure-port-enabled: false
    statusPageUrl: http://${eureka.hostname}:${server.port}/actuator/info
    healthCheckUrl: http://${eureka.hostname}:${server.port}/actuator/health
    homePageUrl: http://${eureka.hostname}:${server.port}/
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${myanimechart_serviceregistry_url}

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  ssl:
    enabled: false
    key-store: ${myanimechart_keystore_path}
    key-store-password: ${myanimechart_keystore_password}
    key-store-type: JKS
    key-alias: ${myanimechart_keystore_alias}
    trust-store: ${myanimechart_truststore_path}
    trust-store-password: ${myanimechart_truststore_password}
    trust-store-type: JKS