spring:
  application:
    name: discovery
  devtools:
    restart:
      poll-interval: 1s
    livereload:
      enabled: true
  config:
    import: file:../myanimechart-core/src/main/resources/application-dev.yml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${myanimechart_serviceregistry_url}