spring:
  application:
    name: serviceregistry
  config:
    import: file:../myanimechart-common/src/main/resources/application.yml

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${myanimechart_serviceregistry_url}