spring:
  application:
    name: collector
  config:
    import: file:../myanimechart-common/src/main/resources/application-dev.yml,file:../myanimechart-database/src/main/resources/application-dev.yml
