spring:
  application:
    name: query
  config:
    import: file:./myanimechart-common/src/main/resources/application.yml,file:./myanimechart-database/src/main/resources/application.yml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
