myanimechart:
  home-url: ${myanimechart_home_url}

myanimelist:
  client-id: ${myanimechart_myanimelist_client_id}
  client-secret: ${myanimechart_myanimelist_client_secret}
  redirect-uri: ${myanimechart_myanimelist_redirect_uri}

spring:
  application:
    name: query
  config:
    import: file:../myanimechart-common/src/main/resources/application-dev.yml

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
