spring:
  application:
    name: myanimechart-monitor
  config:
    import: file:../myanimechart-common/src/main/resources/application.yml,file:../myanimechart-database/src/main/resources/application.yml
